
services:
  # Banco de dados MySQL
  mysql_app:
    image: mysql:8.4.0
    container_name: mysql_app
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:     
      app-network:
        aliases:
          - mysql_app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u","root"]
      interval: 3s
      timeout: 10s
      retries: 5
    restart: always

  # Serviço RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5675:5675"  # Porta AMQP
      - "15675:15675"  # Porta da interface de gerenciamento
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network
    restart: always    
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 3s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: ouro-gourmet-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_app:3306/appdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_INITIALIZATION_TIMEOUT: 30000
      SPRING_RABBITMQ_HOST: rabbitmq  # Comunicação interna via nome do serviço
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_DATASOURCE_URL_FLYWAY: jdbc:mysql://mysql_app:3306/appdb
    depends_on:
      mysql_app:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
volumes:
  mysql_data:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge
    name: app-network  # Força o nome da rede
    attachable: true 
    
